// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/http_config.proto

package http_config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Token                bool     `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2c6387f8519b27c, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetToken() bool {
	if m != nil {
		return m.Token
	}
	return false
}

var E_Api = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Config)(nil),
	Field:         65801,
	Name:          "mig_one.http_config.api",
	Tag:           "bytes,65801,opt,name=api",
	Filename:      "protobuf/http_config.proto",
}

func init() {
	proto.RegisterType((*Config)(nil), "mig_one.http_config.config")
	proto.RegisterExtension(E_Api)
}

func init() { proto.RegisterFile("protobuf/http_config.proto", fileDescriptor_b2c6387f8519b27c) }

var fileDescriptor_b2c6387f8519b27c = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x28, 0x29, 0x29, 0x88, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c,
	0xd7, 0x03, 0x0b, 0x0a, 0x09, 0xe7, 0x66, 0xa6, 0xc7, 0xe7, 0xe7, 0xa5, 0xea, 0x21, 0x49, 0x49,
	0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0xc3, 0xf5, 0xa5, 0xa4, 0x16, 0x27, 0x17, 0x65,
	0x16, 0x94, 0xe4, 0x17, 0x41, 0xb4, 0x29, 0xc9, 0x71, 0xb1, 0x41, 0xd4, 0x0a, 0x89, 0x70, 0xb1,
	0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0x41, 0x38, 0x56, 0xfe,
	0x5c, 0xcc, 0x89, 0x05, 0x99, 0x42, 0x72, 0x7a, 0x10, 0x93, 0xf4, 0x60, 0x26, 0xe9, 0xf9, 0xa6,
	0x96, 0x64, 0xe4, 0xa7, 0xf8, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0x15, 0x4b, 0x74, 0x36, 0xb1, 0x28,
	0x30, 0x6a, 0x70, 0x1b, 0x49, 0xeb, 0x61, 0x71, 0x86, 0x1e, 0x84, 0x0a, 0x02, 0x99, 0xe4, 0x24,
	0x1a, 0x05, 0x73, 0x29, 0xb2, 0x27, 0x92, 0xd8, 0xc0, 0x06, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0xc8, 0x0c, 0xd1, 0xe3, 0x00, 0x00, 0x00,
}
